### ISSUE TITLE
ROR + React Final Capstone (Pawpal App): Kanban board set up

### ISSUE THREAD

**Issue by karlavdelgadof** [karlavdelgadof/final-capstone-frontend#11]
#### Here you can find the link to our kanban boards :arrow_down: 

- [Backend board](https://github.com/users/Hannziegel/projects/4) :gear: 
:camera:
![image](https://user-images.githubusercontent.com/92395484/207670936-d3444396-4aa4-46fe-8053-29a19dd4ca1f.png)
[Backend Repo](https://github.com/Hannziegel/final-capstone-backend) :exclamation: 

- [Frontend board](https://github.com/users/karlavdelgadof/projects/5) :page_facing_up: 
:camera:
![image](https://user-images.githubusercontent.com/92395484/207671004-55737bf7-8fe5-4bc7-a05c-2a8d8d0f4584.png)

 

#### This is our team :people_holding_hands: :technologist: 

@karlavdelgadof :tulip: 
@Hannziegel :jack_o_lantern: 
@karam084 :compass:

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a kanban, that does not contain a screenshot of its state.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by vichuge** [comment]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._

- Adding up the points to every teammate, it looks like @karam084 doesn't have enough points to consider the charge work assigned in a fair way. Please consider the next:

`If some student has significantly (difference >= 5 points) more or fewer points than others - leave a comment in the issue saying that they need to fix it and ask again for a review.`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by karlavdelgadof** [comment]
> Hi dear student,
> 
> Good job so far! You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!
> 
> ![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif) [ ![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif) ](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif) [ ](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)
> 
> ## Suggested changes
> _Check the comments under the review._
> 
> You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._
> 
> * Adding up the points to every teammate, it looks like @karam084 doesn't have enough points to consider the charge work assigned in a fair way. Please consider the next:
> 
> `If some student has significantly (difference >= 5 points) more or fewer points than others - leave a comment in the issue saying that they need to fix it and ask again for a review.`
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
Hi @vichuge! I have already fixed the points and they are evenly balanced taking into consideration our preferred workflow!

**Comment by Meltrust** [comment]
Hi @karlavdelgadof,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Assignations have been balanced ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
